 INGREIDENTS 

▢3 potato / aloo, boiled & grated

▢1 chilli, finely chopped

▢1 tsp ginger garlic paste

▢¼ tsp turmeric

▢½ tsp kashmiri red chilli powder

▢½ tsp cumin powder / jeera powder

▢½ tsp aamchur / dry mango powder

▢½ tsp chaat masala

▢½ tsp salt

▢2 tbsp mint / pudina, chopped

▢2 tbsp coriander, chopped

▢2 tbsp corn flour

▢oil, for frying
                                                        

